services:
    database:
        image: mariadb
        container_name: database
        restart: always
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=goodfood_order_database
            - MYSQL_ROOT_PASSWORD=root
        
        ports:
            - '3306:3306'
        volumes:
            - goodfood_order_database:/var/lib/mysql/ 

    database_administration:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            PMA_USER: root
            PMA_PASSWORD: root
    application:
        depends_on:
            - database
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"

volumes:
    goodfood_order_database:
